"""
The shape of this app: the business it belongs to, and the tabs it has.

Auto-generated -- but this file is meant to be edited. It is the ONE place
that differs from every other app built this way.

Adding a field: put another dict in a module's "fields" list and restart. The
column is created on the next launch; existing records keep their data.

    {"name": "po_number", "label": "PO #", "type": "text", "html": "text",
     "required": False, "wide": False, "options": None, "step": None}

Field types: text, textarea, number, money, date, time, phone, email, select
(needs "options"), check.

Per-module extras:
    sort          ORDER BY clause for the list page
    date_field    which date drives "today" on the dashboard
    sum_field     which number gets totalled at the bottom of the list
    status_field  which select gets colour-coded
    alert         {"field": ..., "vs": ..., "label": ...} -> flags a row when
                  field <= vs (used by Inventory for low stock)
"""

BUSINESS = {'name': 'Conrad is handsome asf',
 'id': 'jake_s_junkyard',
 'tagline': 'take reservations, keep up with staff hours, and track what we owe '
            'suppliers',
 'logo': False,
 'wish_url': 'https://corder-downloads.fly.dev/wish',
 'theme': {'--bg': '#0f2340',
           '--surface': '#16304f',
           '--surface-2': '#1d3d63',
           '--line': '#27507f',
           '--ink': '#e8eef7',
           '--muted': '#9db3cf',
           '--blue': '#5aa9f0',
           '--shadow': 'none'},
 'generated': '2026-08-19 09:59'}

MODULES = [{'key': 'scheduling',
  'label': 'Schedule',
  'icon': '📅',
  'table': 'appointments',
  'singular': 'appointment',
  'fields': [{'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'time',
              'label': 'Time',
              'type': 'time',
              'html': 'time',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'customer',
              'label': 'Customer',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'service',
              'label': 'Truck#',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'staff',
              'label': 'Staff',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Booked', 'Confirmed', 'Done', 'No-show'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': True},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'date, time',
  'date_field': 'date',
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'staff',
  'label': 'Staff',
  'icon': '🧑\u200d🔧',
  'table': 'staff',
  'singular': 'person',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'role',
              'label': 'Role',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'hourly_rate',
              'label': 'Hourly rate',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'daylog',
  'label': 'Daily log',
  'icon': '📊',
  'table': 'day_log',
  'singular': 'entry',
  'fields': [{'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'item',
              'label': 'What',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'amount',
              'label': 'Amount',
              'type': 'number',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '1',
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'date DESC, id DESC',
  'date_field': 'date',
  'sum_field': 'amount',
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'checklists',
  'label': 'Checklists',
  'icon': '☑',
  'table': 'checklist_items',
  'singular': 'task',
  'fields': [{'name': 'task',
              'label': 'Task',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'area',
              'label': 'Area',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'frequency',
              'label': 'How often',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Daily', 'Weekly', 'Monthly'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'done',
              'label': 'Done',
              'type': 'check',
              'html': 'check',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'area, id',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'wishlist',
  'label': 'Wishlist',
  'icon': '💡',
  'table': 'wishlist',
  'singular': 'request',
  'fields': [{'name': 'request',
              'label': 'What would you like changed?',
              'type': 'textarea',
              'html': 'textarea',
              'required': True,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'Looking at it', 'Doing it', 'Done'],
              'owner_only': True,
              'default': 'New',
              'step': None,
              'is_status': True},
             {'name': 'fixed_at',
              'label': 'Fixed',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': True,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': None,
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': True,
  'archive': {'done_value': 'Done',
              'stamp_field': 'fixed_at',
              'hours': 24,
              'done_label': 'Fixed',
              'open_label': 'Pending'}}]


def by_key(key):
    for m in MODULES:
        if m["key"] == key:
            return m
    return None
