"""
The shape of this app: the business it belongs to, and the tabs it has.

Auto-generated -- but this file is meant to be edited. It is the ONE place
that differs from every other app built this way.

Adding a field: put another dict in a module's "fields" list and restart. The
column is created on the next launch; existing records keep their data.

    {"name": "po_number", "label": "PO #", "type": "text", "html": "text",
     "required": False, "wide": False, "options": None, "step": None}

Field types: text, textarea, number, money, date, time, phone, email, select
(needs "options"), check.

Per-module extras:
    sort          ORDER BY clause for the list page
    date_field    which date drives "today" on the dashboard
    sum_field     which number gets totalled at the bottom of the list
    status_field  which select gets colour-coded
    alert         {"field": ..., "vs": ..., "label": ...} -> flags a row when
                  field <= vs (used by Inventory for low stock)
"""

BUSINESS = {'name': "Jackson's",
 'id': 'new_app',
 'tagline': 'keepup with staff and payment',
 'logo': False,
 'wish_url': 'https://corder-downloads.fly.dev/wish',
 'theme': {'--bg': '#f6f6f6',
           '--surface': '#ffffff',
           '--surface-2': '#ededed',
           '--line': '#e0e0e0',
           '--ink': '#141414',
           '--muted': '#5f5f5f',
           '--blue': '#d63400',
           '--green': '#1f7a4d',
           '--header-bg': '#ffffff',
           '--header-ink': '#111111',
           '--header-muted': '#555555',
           '--header-nav': '#f3f3f3',
           '--header-line': '#e0e0e0'},
 'theme_key': 'midnight',
 'mode': 'dark',
 'style': {'look': 'split',
           'nav': 'plain',
           'btn': '',
           'hero': True,
           'strip': True,
           'loud': 'on',
           'vars': {'--head-weight': '800',
                    '--head-space': '-.03em',
                    '--head-size': '32px',
                    '--radius': '14px',
                    '--radius-sm': '10px',
                    '--radius-btn': '999px',
                    '--nav-case': 'none',
                    '--nav-track': '0',
                    '--nav-size': '14px',
                    '--hero-bg': '#020202',
                    '--hero-ink': '#ffffff',
                    '--hero-glow': 'rgba(255,60,0,.34)',
                    '--hero-glow-2': 'rgba(255,60,0,.13)',
                    '--strip-bg': '#111312',
                    '--strip-ink': '#d8d8d8'}},
 'initials': 'JS',
 'generated': '2026-09-01 10:25'}

MODULES = [{'key': 'staff',
  'label': 'Staff',
  'icon': '👷',
  'table': 'staff',
  'singular': 'person',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'role',
              'label': 'Role',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'hourly_rate',
              'label': 'Per hour',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': False,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None},
 {'key': 'timeclock',
  'label': 'Hours',
  'icon': '⏱',
  'table': 'time_entries',
  'singular': 'entry',
  'fields': [{'name': 'staff',
              'label': 'Who',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'date',
              'label': 'Day',
              'type': 'date',
              'html': 'date',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'hours',
              'label': 'Hours worked',
              'type': 'number',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.25',
              'off': False,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'date DESC, id DESC',
  'date_field': 'date',
  'sum_field': 'hours',
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'hours',
  'pay_from': {'tab': 'staff', 'match': 'staff', 'rate': 'hourly_rate'},
  'owed_from': None},
 {'key': 'expenses',
  'label': 'Payments',
  'icon': '💵',
  'table': 'expenses',
  'singular': 'expense',
  'fields': [{'name': 'date',
              'label': 'Paid on',
              'type': 'date',
              'html': 'date',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'vendor',
              'label': 'Paid to',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'amount',
              'label': 'Amount',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': False,
              'is_status': False},
             {'name': 'category',
              'label': 'What for',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Wages', 'Bonus', 'Expenses', 'Other'],
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'date DESC, id DESC',
  'date_field': 'date',
  'sum_field': 'amount',
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None},
 {'key': 'wishlist',
  'label': 'Wishlist',
  'icon': '💡',
  'table': 'wishlist',
  'singular': 'request',
  'fields': [{'name': 'request',
              'label': 'What would you like changed?',
              'type': 'textarea',
              'html': 'textarea',
              'required': True,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'Looking at it', 'Doing it', 'Done'],
              'owner_only': True,
              'default': 'New',
              'step': None,
              'off': False,
              'is_status': True},
             {'name': 'fixed_at',
              'label': 'Fixed',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': True,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': None,
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': True,
  'archive': {'done_value': 'Done',
              'stamp_field': 'fixed_at',
              'hours': 24,
              'done_label': 'Fixed',
              'open_label': 'Pending'},
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None}]


def by_key(key):
    for m in MODULES:
        if m["key"] == key:
            return m
    return None
