"""
The shape of this app: the business it belongs to, and the tabs it has.

Auto-generated -- but this file is meant to be edited. It is the ONE place
that differs from every other app built this way.

Adding a field: put another dict in a module's "fields" list and restart. The
column is created on the next launch; existing records keep their data.

    {"name": "po_number", "label": "PO #", "type": "text", "html": "text",
     "required": False, "wide": False, "options": None, "step": None}

Field types: text, textarea, number, money, date, time, phone, email, select
(needs "options"), check.

Per-module extras:
    sort          ORDER BY clause for the list page
    date_field    which date drives "today" on the dashboard
    sum_field     which number gets totalled at the bottom of the list
    status_field  which select gets colour-coded
    alert         {"field": ..., "vs": ..., "label": ...} -> flags a row when
                  field <= vs (used by Inventory for low stock)
"""

BUSINESS = {'name': '2men and a truck',
 'id': 'new_app',
 'tagline': 'software needs to def help with sheduling.',
 'logo': True,
 'wish_url': 'https://corder-downloads.fly.dev/wish',
 'theme': {'--bg': '#eef4fc',
           '--surface': '#ffffff',
           '--surface-2': '#e3ecf9',
           '--line': '#cfdcee',
           '--ink': '#16233a',
           '--muted': '#5d7292',
           '--blue': '#1565c0'},
 'theme_key': 'default',
 'initials': '2T',
 'generated': '2026-08-28 13:44'}

MODULES = [{'key': 'customers',
  'label': 'Customers',
  'icon': '👤',
  'table': 'customers',
  'singular': 'customer',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'address',
              'label': 'Address',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'scheduling',
  'label': 'Schedule',
  'icon': '📅',
  'table': 'appointments',
  'singular': 'appointment',
  'fields': [{'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'time',
              'label': 'Time',
              'type': 'time',
              'html': 'time',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'customer',
              'label': 'Customer',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'service',
              'label': 'Service',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'staff',
              'label': 'Staff',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Booked', 'Confirmed', 'Done', 'No-show'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': True},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'date, time',
  'date_field': 'date',
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'jobs',
  'label': 'Jobs',
  'icon': '🛠',
  'table': 'jobs',
  'singular': 'job',
  'fields': [{'name': 'customer',
              'label': 'Customer',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'truck',
              'label': 'Truck #',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'movers',
              'label': 'Movers',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'due',
              'label': 'Day of move',
              'type': 'date',
              'html': 'date',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'title',
              'label': 'Job',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'In progress', 'Waiting', 'Done'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': True},
             {'name': 'price',
              'label': 'Price',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': 'due',
  'sum_field': 'price',
  'status_field': 'status',
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'staff',
  'label': 'Staff',
  'icon': '🧑\u200d🔧',
  'table': 'staff',
  'singular': 'person',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'role',
              'label': 'Role',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'hourly_rate',
              'label': 'Hourly rate',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'notes',
  'label': 'Notes',
  'icon': '🗒',
  'table': 'notes',
  'singular': 'note',
  'fields': [{'name': 'title',
              'label': 'Title',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'body',
              'label': 'Note',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': 'date',
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None},
 {'key': 'wishlist',
  'label': 'Wishlist',
  'icon': '💡',
  'table': 'wishlist',
  'singular': 'request',
  'fields': [{'name': 'request',
              'label': 'What would you like changed?',
              'type': 'textarea',
              'html': 'textarea',
              'required': True,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'Looking at it', 'Doing it', 'Done'],
              'owner_only': True,
              'default': 'New',
              'step': None,
              'is_status': True},
             {'name': 'fixed_at',
              'label': 'Fixed',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': True,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': None,
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': True,
  'archive': {'done_value': 'Done',
              'stamp_field': 'fixed_at',
              'hours': 24,
              'done_label': 'Fixed',
              'open_label': 'Pending'}}]


def by_key(key):
    for m in MODULES:
        if m["key"] == key:
            return m
    return None
