"""
The shape of this app: the business it belongs to, and the tabs it has.

Auto-generated -- but this file is meant to be edited. It is the ONE place
that differs from every other app built this way.

Adding a field: put another dict in a module's "fields" list and restart. The
column is created on the next launch; existing records keep their data.

    {"name": "po_number", "label": "PO #", "type": "text", "html": "text",
     "required": False, "wide": False, "options": None, "step": None}

Field types: text, textarea, number, money, date, time, phone, email, select
(needs "options"), check.

Per-module extras:
    sort          ORDER BY clause for the list page
    date_field    which date drives "today" on the dashboard
    sum_field     which number gets totalled at the bottom of the list
    status_field  which select gets colour-coded
    alert         {"field": ..., "vs": ..., "label": ...} -> flags a row when
                  field <= vs (used by Inventory for low stock)
"""

BUSINESS = {'name': "L's hair salon",
 'id': 'l_s_hair_salon',
 'tagline': 'need scheduling app to help me manage my callender and payment and '
            'somwhere the customers can book a appointment',
 'logo': False,
 'wish_url': 'https://corder-downloads.fly.dev/wish',
 'theme': {'--bg': '#fff0f6',
           '--surface': '#ffffff',
           '--surface-2': '#ffe1ee',
           '--line': '#f3c2d8',
           '--ink': '#3a1d2b',
           '--muted': '#8b5f74',
           '--blue': '#c9266f',
           '--green': '#2e7d5b'},
 'theme_key': 'pink',
 'mode': '',
 'style': {'look': '',
           'nav': '',
           'btn': '',
           'hero': False,
           'strip': False,
           'loud': '',
           'vars': {}},
 'initials': 'LS',
 'generated': '2026-09-01 10:25'}

MODULES = [{'key': 'customers',
  'label': 'Clients',
  'icon': '👤',
  'table': 'customers',
  'singular': 'customer',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'mobile',
              'label': 'Mobile',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'formula',
              'label': 'Colour formula & notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'allergies',
              'label': 'Allergies / patch test',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'source',
              'label': 'How they found us',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'address',
              'label': 'Address',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'billing',
              'label': 'Billing address',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'company',
              'label': 'Company',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None},
 {'key': 'scheduling',
  'label': 'Appointments',
  'icon': '✂️',
  'table': 'appointments',
  'singular': 'appointment',
  'fields': [{'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'time',
              'label': 'Time',
              'type': 'time',
              'html': 'time',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'customer',
              'label': 'Client',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'service',
              'label': 'Service',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'staff',
              'label': 'Stylist',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': 'Layla',
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'price',
              'label': 'Price',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': False,
              'is_status': False},
             {'name': 'deposit',
              'label': 'Deposit paid',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': True,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Booked', 'Confirmed', 'Done', 'Paid', 'No-show'],
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': True},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'date, time',
  'date_field': 'date',
  'sum_field': 'price',
  'status_field': 'status',
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': {'total': 'price', 'paid': 'deposit'}},
 {'key': 'products',
  'label': 'Services',
  'icon': '💈',
  'table': 'products',
  'singular': 'product',
  'fields': [{'name': 'name',
              'label': 'Service',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'category',
              'label': 'Type',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'price',
              'label': 'Price',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': False,
              'is_status': False},
             {'name': 'minutes',
              'label': 'How long (mins)',
              'type': 'number',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '1',
              'off': False,
              'is_status': False},
             {'name': 'description',
              'label': 'What it covers',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'active',
              'label': 'Still offered',
              'type': 'check',
              'html': 'check',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'category, name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None},
 {'key': 'staff',
  'label': 'Stylists',
  'icon': '💇',
  'table': 'staff',
  'singular': 'person',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'role',
              'label': 'Chair / speciality',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'hourly_rate',
              'label': 'Per hour',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'off': False,
              'is_status': False},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None},
 {'key': 'wishlist',
  'label': 'Wishlist',
  'icon': '💡',
  'table': 'wishlist',
  'singular': 'request',
  'fields': [{'name': 'request',
              'label': 'What would you like changed?',
              'type': 'textarea',
              'html': 'textarea',
              'required': True,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'Looking at it', 'Doing it', 'Done'],
              'owner_only': True,
              'default': 'New',
              'step': None,
              'off': False,
              'is_status': True},
             {'name': 'fixed_at',
              'label': 'Fixed',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': True,
              'default': None,
              'step': None,
              'off': False,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': None,
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': True,
  'archive': {'done_value': 'Done',
              'stamp_field': 'fixed_at',
              'hours': 24,
              'done_label': 'Fixed',
              'open_label': 'Pending'},
  'sum_unit': 'money',
  'pay_from': None,
  'owed_from': None}]


def by_key(key):
    for m in MODULES:
        if m["key"] == key:
            return m
    return None
