"""
The shape of this app: the business it belongs to, and the tabs it has.

Auto-generated -- but this file is meant to be edited. It is the ONE place
that differs from every other app built this way.

Adding a field: put another dict in a module's "fields" list and restart. The
column is created on the next launch; existing records keep their data.

    {"name": "po_number", "label": "PO #", "type": "text", "html": "text",
     "required": False, "wide": False, "options": None, "step": None}

Field types: text, textarea, number, money, date, time, phone, email, select
(needs "options"), check.

Per-module extras:
    sort          ORDER BY clause for the list page
    date_field    which date drives "today" on the dashboard
    sum_field     which number gets totalled at the bottom of the list
    status_field  which select gets colour-coded
    alert         {"field": ..., "vs": ..., "label": ...} -> flags a row when
                  field <= vs (used by Inventory for low stock)
"""

BUSINESS = {'name': "Sarah's Florist Shop",
 'id': 'sarah_s_florist_shop',
 'tagline': 'help keepup with jobs. when and where the jobs are',
 'logo': False,
 'wish_url': 'https://corder-downloads.fly.dev/wish',
 'theme': {'--bg': '#fbf8ef',
           '--surface': '#ffffff',
           '--surface-2': '#eff0e2',
           '--line': '#dcdac6',
           '--ink': '#262b16',
           '--muted': '#69704f',
           '--blue': '#3c4619',
           '--green': '#3c4619',
           '--header-bg': '#3c4619',
           '--header-ink': '#f6f5ea',
           '--header-muted': '#c9d0ae',
           '--header-nav': '#333d15',
           '--header-line': '#5a6630'},
 'theme_key': 'sage',
 'mode': 'light',
 'style': {'look': 'centred',
           'nav': 'plain',
           'btn': 'outline',
           'hero': False,
           'strip': False,
           'loud': '',
           'vars': {'--font-head': 'Georgia, Times New Roman, serif',
                    '--head-weight': '400',
                    '--head-space': '0',
                    '--head-size': '34px',
                    '--radius': '3px',
                    '--radius-sm': '3px'}},
 'initials': 'SS',
 'generated': '2026-08-31 16:05'}

MODULES = [{'key': 'jobs',
  'label': 'Orders',
  'icon': '💐',
  'table': 'jobs',
  'singular': 'job',
  'fields': [{'name': 'customer',
              'label': 'Customer',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'title',
              'label': 'What they want',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'occasion',
              'label': 'Occasion',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Birthday',
                          'Anniversary',
                          'Wedding',
                          'Funeral',
                          'New baby',
                          'Thank you',
                          'Just because'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'due',
              'label': 'Needed by',
              'type': 'date',
              'html': 'date',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'going_to',
              'label': "Where it's going",
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'for_when',
              'label': 'Collecting or delivering',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Collecting', 'Delivering'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'card_message',
              'label': 'Card message',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'price',
              'label': 'Price',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['Taken', 'Being made', 'Ready', 'Gone out', 'Done'],
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': True},
             {'name': 'notes',
              'label': 'Notes',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': 'due',
  'sum_field': 'price',
  'status_field': 'status',
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None},
 {'key': 'customers',
  'label': 'Customers',
  'icon': '👤',
  'table': 'customers',
  'singular': 'customer',
  'fields': [{'name': 'name',
              'label': 'Name',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'phone',
              'label': 'Phone',
              'type': 'phone',
              'html': 'tel',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'email',
              'label': 'Email',
              'type': 'email',
              'html': 'email',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'address',
              'label': 'Address',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'notes',
              'label': 'What they usually like',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'name COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None},
 {'key': 'inventory',
  'label': 'Stock',
  'icon': '🌷',
  'table': 'inventory',
  'singular': 'item',
  'fields': [{'name': 'item',
              'label': 'Flower / item',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'qty',
              'label': 'How many left',
              'type': 'number',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '1',
              'is_status': False},
             {'name': 'reorder_at',
              'label': 'Order more at',
              'type': 'number',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '1',
              'is_status': False},
             {'name': 'supplier',
              'label': 'Grower',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'price',
              'label': 'Cost each',
              'type': 'money',
              'html': 'number',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': '0.01',
              'is_status': False}],
  'sort': 'item COLLATE NOCASE',
  'date_field': None,
  'sum_field': None,
  'status_field': None,
  'alert': {'field': 'qty', 'vs': 'reorder_at', 'label': 'low stock'},
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None},
 {'key': 'notes',
  'label': 'Notes',
  'icon': '🗒',
  'table': 'notes',
  'singular': 'note',
  'fields': [{'name': 'title',
              'label': 'Title',
              'type': 'text',
              'html': 'text',
              'required': True,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'date',
              'label': 'Date',
              'type': 'date',
              'html': 'date',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'body',
              'label': 'Note',
              'type': 'textarea',
              'html': 'textarea',
              'required': False,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': 'date',
  'sum_field': None,
  'status_field': None,
  'alert': None,
  'show_added': False,
  'archive': None,
  'sum_unit': 'money',
  'pay_from': None},
 {'key': 'wishlist',
  'label': 'Wishlist',
  'icon': '💡',
  'table': 'wishlist',
  'singular': 'request',
  'fields': [{'name': 'request',
              'label': 'What would you like changed?',
              'type': 'textarea',
              'html': 'textarea',
              'required': True,
              'wide': True,
              'options': None,
              'owner_only': False,
              'default': None,
              'step': None,
              'is_status': False},
             {'name': 'status',
              'label': 'Status',
              'type': 'select',
              'html': 'select',
              'required': False,
              'wide': False,
              'options': ['New', 'Looking at it', 'Doing it', 'Done'],
              'owner_only': True,
              'default': 'New',
              'step': None,
              'is_status': True},
             {'name': 'fixed_at',
              'label': 'Fixed',
              'type': 'text',
              'html': 'text',
              'required': False,
              'wide': False,
              'options': None,
              'owner_only': True,
              'default': None,
              'step': None,
              'is_status': False}],
  'sort': 'id DESC',
  'date_field': None,
  'sum_field': None,
  'status_field': 'status',
  'alert': None,
  'show_added': True,
  'archive': {'done_value': 'Done',
              'stamp_field': 'fixed_at',
              'hours': 24,
              'done_label': 'Fixed',
              'open_label': 'Pending'},
  'sum_unit': 'money',
  'pay_from': None}]


def by_key(key):
    for m in MODULES:
        if m["key"] == key:
            return m
    return None
